FROM mdillon/postgis:10-alpine
ENV POSTGRES_USER=postgres
ENV POSTGRES_DB=CSM_db
ENV PGDATA=/home/postgres/csm_db

WORKDIR /app

COPY . /app

## bring in the csm dataset in csv (1.5G)
## and build up the data/sql directory
RUN cd /app/schema && \
    wget -nv https://g-c662a6.a78b8.36fe.data.globus.org/cxm/models/csm/csm_csv.tar.gz && \
    tar zxvf csm_csv.tar.gz

RUN mkdir /home/postgres
RUN chown postgres /home/postgres
RUN su postgres -c /app/doc/run-as-postgres

RUN echo "host all  all    0.0.0.0/0  trust" >> /home/postgres/csm_db/pg_hba.conf


