# Use postgres/example user/password credentials
version: '2.2'

services:

  db:
    build:
      dockerfile: Dockerfile-postgis
      context: ./
    restart: always
    environment:
      name: edric
      POSTGRES_PASSWORD: example

  web:
    build:
      dockerfile: Dockerfile-web
      context: ./
    restart: always
    ports:
      - 8094:8081
      - 8095:80

