#!/bin/bash

dropdb --if-exists CSM_db 
createdb CSM_db

psql postgresql://postgres:example@localhost/CSM_db << AAA

  CREATE EXTENSION postgis;
  SELECT PostGIS_Version();

  \i '/home/postgres/CSM/sql/setup_model_schema.sql';
  \i '/home/postgres/CSM/sql/setup_model_tb.sql';
  \i '/home/postgres/CSM/sql/setup_meta_schema.sql';
  \i '/home/postgres/CSM/sql/setup_meta_tb.sql';
  \i '/home/postgres/CSM/sql/linkup_traces.sql';

  DROP ROLE webonly;
  CREATE ROLE webonly WITH LOGIN PASSWORD 'scec';
  GRANT SELECT ON ALL TABLES IN SCHEMA public TO webonly;
  REVOKE CREATE ON SCHEMA public FROM PUBLIC;

  \dp
  \q

AAA

