UPDATE FlatMaxwell_tb SET geom = ST_SetSRID(ST_MakePoint(LON,LAT),4326); 
CREATE INDEX ON FlatMaxwell_tb USING GIST ("geom");
UPDATE FlatMaxwell_meta SET dataset_name = %%CSMTB%;
UPDATE FlatMaxwell_tb SET meta_gid = select gid from CSM_meta where dataset_name = %%CSMTB%;
UPDATE Hardebeck_FM_tb SET geom = ST_SetSRID(ST_MakePoint(LON,LAT),4326); 
CREATE INDEX ON Hardebeck_FM_tb USING GIST ("geom");
UPDATE Hardebeck_FM_meta SET dataset_name = %%CSMTB%;
UPDATE Hardebeck_FM_tb SET meta_gid = select gid from CSM_meta where dataset_name = %%CSMTB%;
UPDATE LovelessMeade_tb SET geom = ST_SetSRID(ST_MakePoint(LON,LAT),4326); 
CREATE INDEX ON LovelessMeade_tb USING GIST ("geom");
UPDATE LovelessMeade_meta SET dataset_name = %%CSMTB%;
UPDATE LovelessMeade_tb SET meta_gid = select gid from CSM_meta where dataset_name = %%CSMTB%;
UPDATE Luttrell-2017_tb SET geom = ST_SetSRID(ST_MakePoint(LON,LAT),4326); 
CREATE INDEX ON Luttrell-2017_tb USING GIST ("geom");
UPDATE Luttrell-2017_meta SET dataset_name = %%CSMTB%;
UPDATE Luttrell-2017_tb SET meta_gid = select gid from CSM_meta where dataset_name = %%CSMTB%;
UPDATE NeoKinema_tb SET geom = ST_SetSRID(ST_MakePoint(LON,LAT),4326); 
CREATE INDEX ON NeoKinema_tb USING GIST ("geom");
UPDATE NeoKinema_meta SET dataset_name = %%CSMTB%;
UPDATE NeoKinema_tb SET meta_gid = select gid from CSM_meta where dataset_name = %%CSMTB%;
UPDATE SAFPoly3D_tb SET geom = ST_SetSRID(ST_MakePoint(LON,LAT),4326); 
CREATE INDEX ON SAFPoly3D_tb USING GIST ("geom");
UPDATE SAFPoly3D_meta SET dataset_name = %%CSMTB%;
UPDATE SAFPoly3D_tb SET meta_gid = select gid from CSM_meta where dataset_name = %%CSMTB%;
UPDATE SHELLS_tb SET geom = ST_SetSRID(ST_MakePoint(LON,LAT),4326); 
CREATE INDEX ON SHELLS_tb USING GIST ("geom");
UPDATE SHELLS_meta SET dataset_name = %%CSMTB%;
UPDATE SHELLS_tb SET meta_gid = select gid from CSM_meta where dataset_name = %%CSMTB%;
UPDATE UCERF3_ABM_tb SET geom = ST_SetSRID(ST_MakePoint(LON,LAT),4326); 
CREATE INDEX ON UCERF3_ABM_tb USING GIST ("geom");
UPDATE UCERF3_ABM_meta SET dataset_name = %%CSMTB%;
UPDATE UCERF3_ABM_tb SET meta_gid = select gid from CSM_meta where dataset_name = %%CSMTB%;
UPDATE YH14-K_tb SET geom = ST_SetSRID(ST_MakePoint(LON,LAT),4326); 
CREATE INDEX ON YH14-K_tb USING GIST ("geom");
UPDATE YH14-K_meta SET dataset_name = %%CSMTB%;
UPDATE YH14-K_tb SET meta_gid = select gid from CSM_meta where dataset_name = %%CSMTB%;
UPDATE YHSM-2013_tb SET geom = ST_SetSRID(ST_MakePoint(LON,LAT),4326); 
CREATE INDEX ON YHSM-2013_tb USING GIST ("geom");
UPDATE YHSM-2013_meta SET dataset_name = %%CSMTB%;
UPDATE YHSM-2013_tb SET meta_gid = select gid from CSM_meta where dataset_name = %%CSMTB%;
UPDATE Zeng_tb SET geom = ST_SetSRID(ST_MakePoint(LON,LAT),4326); 
CREATE INDEX ON Zeng_tb USING GIST ("geom");
UPDATE Zeng_meta SET dataset_name = %%CSMTB%;
UPDATE Zeng_tb SET meta_gid = select gid from CSM_meta where dataset_name = %%CSMTB%;
